name: Build
on:
  pull_request:
  push:
    branches:
      - master
jobs:
  test:
    name: Run tests ${{matrix.sdk}} on ${{matrix.os}}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        sdk: ['stable']
    runs-on: ${{ matrix.os }}
    steps:
      - uses: dart-lang/setup-dart@v1
        with:
          sdk: ${{ matrix.sdk }}
      - uses: actions/checkout@v4
      - run: dart --version
      - run: dart pub get
      - run: dart analyze --fatal-infos .
      - run: dart test
      - run: dart tool/format.dart
      - name: "check for uncommitted changes"
        run: dart tool/check_uncommitted_changes.dart
